spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
      timeout: 600000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/psad?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.lince.entity
  configuration:
    map-underscore-to-camel-case: true
